name: 'Configure Git'
description: 'Configure Git'
author: jtacopt

inputs:
  branch:
    description: 'GitHub Pages Branch'
    default: 'gh_page'
    required: false
  artifact-name:
    description: 'Page Artifact Source'
    required: true
  path:
    description: 'Page Path'
    default: ''
    required: true
  token:
    description: 'Git Token'
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Get Page Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}

    - name: Deploy Page
      shell: bash
      run: |
        git config --local user.email "jtacopt@gmail.com"
        git config --local user.name "João Carvalho"
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}
        git add ${{ inputs.path }}
        git commit -m "Allure Report | ${{ inputs.path }} | ${{ github.run_number }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}