[server]
port=4444

[node]
detect-drivers = true

[relay]
url = "https://ondemand.eu-central-1.saucelabs.com:443/wd/hub"
configs = [
    "5", '{"browserName": "chrome", "platformName": "Windows 11", "browserVersion": "104"}',
    "10", '{"browserName": "firefox", "platformName": "Windows 10", "browserVersion": "103"}',
    "5", '{"browserName": "safari", "platformName": "macOS 12", "browserVersion": "15"}',
    "2", '{"browserName": "safari", "platformName": "iOS", "appium:platformVersion": "15.4", "appium:deviceName": "iPhone 13 Simulator"}',
    "2", '{"browserName": "chrome", "platformName": "android", "appium:platformVersion": "12.0", "appium:deviceName": "Google Pixel 6 Pro GoogleAPI Emulator"}'
]