name: Test

on: [ push ]
jobs:
  tests:
    name: Run Tests

    permissions:
      contents: write
      pages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows
          - mac
          - linux
        platform-version:
          - latest
        app:
          - chrome
          - firefox
        include:
          - platform: mac
            platform-version: latest
            app: safari
          - platform: windows
            platform-version: latest
            app: edge
          - platform: mac
            platform-version: latest
            app: edge
          - platform: ios
            platform-version: latest
            app: safari
          - platform: android
            platform-version: 12
            app: chrome
          - platform: android
            platform-version: 14
            app: chrome

    uses: ./.github/workflows/run-ui-test.yml
    with:
      platform: ${{ matrix.platform }}
      platform-version: ${{ matrix.platform-version }}
      app: ${{ matrix.app }}
    secrets: inherit

