name: Test

on: [ push ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
        platform:
          - win
          - mac
          - linux
        include:
          - browser: safari
            platform: mac
          - browser: edge
            platform: win
          - browser: edge
            platform: mac

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: make test allure.results.directory:=target/${{ matrix.platform }}/${{ matrix.browser }}/allure-results
        env:
          PLATFORM: ${{ matrix.platform }}
          BROWSER: ${{ matrix.browser }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.platform }}/${{ matrix.browser }}/allure-results
          path: target/${{ matrix.platform }}/${{ matrix.browser }}/allure-results
          retention-days: 1