name: Test

on: [ push ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
        os:
          - win
          - mac
          - linux
        include:
          - browser: safari
            os: mac
          - browser: edge
            os: win
          - browser: edge
            os: mac

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: make test
        env:
          OS: ${{ matrix.os }}
          BROWSER: ${{ matrix.browser }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.platform }}_${{ matrix.browser }}_allure-results
          path: target/allure-results
          retention-days: 1

      - name: Generate Report
        run: make report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.platform }}_${{ matrix.browser }}_allure-report
          path: target/site/allure-maven-plugin
          retention-days: 1
