name: Test

on: [ push ]
jobs:
  linux-tests:
    name: Test Linux
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
          - ${{ matrix.platform == 'win' || matrix.platform == 'mac' ? 'edge' : '' }}
          - ${{ matrix.platform == 'mac' ? 'safari' : '' }}
        platform:
          - win
          - mac
          - linux

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: make test
        env:
          PLATFORM: LINUX
          BROWSER: ${{ matrix.browser }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  win-tests:
    name: Test Windows
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome','firefox' ,'edge']

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: make test
        env:
          PLATFORM: WIN
          BROWSER: ${{ matrix.browser }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  mac-tests:
    name: Test MAC
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome','firefox' ,'edge','safari']

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: make test
        env:
          PLATFORM: mac
          BROWSER: ${{ matrix.browser }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}