name: Test

on: [ push ]
jobs:
  tests:
    name: Run Tests

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
        os:
          - win
          - mac
          - linux
        include:
          - browser: safari
            os: mac
          - browser: edge
            os: win
          - browser: edge
            os: mac

    uses: ./.github/workflows/run-ui-test.yml
    with:
      os: ${{ matrix.os }}
      browser: ${{ matrix.browser }}
    secrets: inherit
