name: Test

on: [ push ]
jobs:
  tests:
    name: Run Tests

    permissions:
      contents: write
      pages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
        platform:
          - win
          - mac
          - linux
        include:
          - browser: safari
            platform: mac
          - browser: edge
            platform: win
          - browser: edge
            platform: mac

    uses: ./.github/workflows/run-ui-test.yml
    with:
      platform: ${{ inputs.platform }}
      browser: ${{ inputs.browser }}
    secrets: inherit

