name: Test

on: [ push ]
jobs:
  tests:
    name: Tests

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
        platform:
          - win
          - mac
          - linux
        include:
          - browser: safari
            platform: mac
          - browser: edge
            platform: win
          - browser: edge
            platform: mac

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: make test
        env:
          PLATFORM: ${{ matrix.platform }}
          BROWSER: ${{ matrix.browser }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.platform }}_${{ matrix.browser }}_allure-results
          path: target/allure-results
          retention-days: 1

      - name: Generate Report
        run: make report

      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ matrix.platform }}_${{ matrix.browser }}_allure-report
          path: target/site/allure-maven-plugin

      - run: rm -r ./*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh_pages

      - name: Get Page Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.platform }}_${{ matrix.browser }}_allure-report
          path: ${{ matrix.platform }}/${{ matrix.browser }}

      - name: Upload Page
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add ${{ matrix.platform }}/${{ matrix.browser }}
          git commit -m "Commit message"
          git push

# Funciona para uma pagina
#    steps:
#      - name:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2
#        with:
#          artifact_name: ${{ matrix.platform }}_${{ matrix.browser }}_allure-report
