name: Test

on: [ push ]
jobs:
  tests:
    name: Run Tests

    permissions:
      contents: write
      pages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows
          - mac
          - linux
        browser:
          - chrome
          - firefox
        include:
          - platform: mac
            browser: safari
          - platform: windows
            browser: edge
          - platform: mac
            browser: edge
          - platform: ios
            browser: safari

    uses: ./.github/workflows/run-ui-test.yml
    with:
      platform: ${{ matrix.platform }}
      browser: ${{ matrix.browser }}
    secrets: inherit

