name: Trigger Smoke Tests

on:

  schedule:
    - cron: '*/1 * * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Test Environment'
        required: true
        type: string

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Smoke Tests
        run: |
          final_value="initial value"
          manual_trigger_value=${{ github.event.inputs.test-type }}
          if [[ -z $manual_trigger_value ]]
          then
            final_value=$manual_trigger_value
          else
            final_value="Trigger By Schedule"
          fi
          echo "Running Smoke Tests on $final_value"
