name: Trigger Smoke Tests

on:

  schedule:
    - cron: '*/1 * * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Test Environment'
        required: true
        type: string

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Smoke Tests
        run: |
          event_type="${{ github.event_name }}"
          if [ "$event_type" == "workflow_dispatch" ]; then
            echo "Running Smoke Tests By workflow_dispatch value: ${{ github.event.inputs.test-type }}"
          elif [ "$event_type" == "schedule" ]; then
            echo "Running Smoke Tests By scheduled event"
          fi
          else
            echo "Unknown trigger type: $event_type"
          fi
        
