name: Trigger Smoke Tests

on:

  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Test Environment'
        required: true
        type: string

jobs:
  smoke-tests:
    runs-on: nebula-runners
    steps:
      - name: Run Smoke Tests
        run: |
          final_value="initial value"
          manual_trigger_value=${{ github.event.inputs.test-type }}
          if [ ! -z manual_trigger_value ]
          then
            final_value="Trigger By Manual
          else
            final_value="Trigger By Schedule"
          fi
          echo "Running Smoke Tests on $value"